create role guest with createrole;
grant select on postgres.public.show to guest;
grant select on postgres.public.animal to guest;
grant select on postgres.public.breed to guest;
grant select on postgres.public.species to guest;
grant select on postgres.public.score to guest;
grant select on postgres.public.standard to guest;
grant select on postgres.public.animalshow to guest;
grant select on postgres.public.usershow to guest;
grant select on postgres.public."group" to guest;
grant select on postgres.public.certificate to guest;
grant select, insert on postgres.public."user" to guest;

create role admin with createrole;
grant select, insert, update, delete on postgres.public.show to admin;
grant select, insert, update, delete on postgres.public.animal to admin;
grant select, insert, update, delete on postgres.public.breed to admin;
grant select, insert, update, delete on postgres.public.species to admin;
grant select, insert, update, delete on postgres.public.score to admin;
grant select, insert, update, delete on postgres.public.standard to admin;
grant select, insert, update, delete on postgres.public.animalshow to admin;
grant select, insert, update, delete on postgres.public.usershow to admin;
grant select, insert, update, delete on postgres.public."group" to admin;
grant select, insert, update, delete on postgres.public.certificate to admin;
grant select, insert, update, delete on postgres.public."user" to admin;

create role breeder;
grant select on postgres.public.show to breeder;
grant select on postgres.public.breed to breeder;
grant select on postgres.public.species to breeder;
grant select on postgres.public.standard to breeder;
grant select on postgres.public.usershow to breeder;
grant select on postgres.public."group" to breeder;
grant select on postgres.public.certificate to breeder;
grant select, insert, update, delete on postgres.public.animal to breeder;
grant select, insert, update on postgres.public.score to breeder;
grant select, insert, update on postgres.public.animalshow to breeder;
grant select, insert, update on postgres.public."user" to breeder;

create role judge;
grant select on postgres.public.show to judge;
grant select on postgres.public.animal to judge;
grant select on postgres.public.breed to judge;
grant select on postgres.public.species to judge;
grant select on postgres.public.standard to judge;
grant select on postgres.public.animalshow to judge;
grant select on postgres.public."group" to judge;
grant select on postgres.public.certificate to judge;
grant select, insert, update on postgres.public."user" to judge;
grant select, insert, update on postgres.public.usershow to judge;
grant select, insert, update on postgres.public.score to judge;
