version: '3.9'

services:
  postgres:
    image: library/postgres:14-bullseye
    container_name: postgres-app
    restart: on-failure
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./.data/app/database/data:/app/database/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - backend

  pg_admin:
    container_name: pgadmin4-app
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
    networks:
      - backend

  app:
    container_name: petowo-app
    restart: on-failure
    environment:
      - DB_NAME
      - DB_USER
      - DB_PWD
      - DB_PORT
      - APP_PORT
    build:
        context: .
        dockerfile: Dockerfile
    command: ["/app/docker/app.sh"]
    depends_on:
        postgres:
          condition: service_healthy
    volumes:
#      - migrations-data:/app/migrations/versions
      - ./.data/app/database/data:/app/database/data
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis-app
    command: --port $REDIS_PORT --save 60 1
    volumes:
      - ./.data/redis:/var/lib/redis
      - ./.data/redis-config:/usr/local/etc/storage/redis.conf
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: on-failure
    environment:
      - ALLOW_EMPTY_PASSWORD
      - REDIS_DISABLE_COMMANDS
      - REDIS_PASSWORD
      - REDIS_USER
      - REDIS_USER_PASSWORD
      - REDIS_PORT
    networks:
      - backend

volumes:
  db-data:
  migrations-data:


networks:
  backend:
    name: "backend"
    driver: bridge
